DROP DATABASE FACTURACION;
CREATE DATABASE FACTURACION;
USE FACTURACION;

-- Table: CLIENTE
CREATE TABLE CLIENTE (
    IDCLI int IDENTITY(1,1),
    NOMCLI varchar(50),
    APEPATCLI varchar(50),
    APEMATCLI varchar(50) ,
    DIRCLI varchar(50),
    TELFCLI CHAR(9),
    CONSTRAINT CLIENTE_pk PRIMARY KEY  (IDCLI)
);

-- Table: FACTURA
CREATE TABLE FACTURA (
    CODFAC int  IDENTITY(1,1) ,
	FECHFAC date  ,
    IDCLI int  , 
    TOTFAC MONEY,
	DESCFAC MONEY,
	IGV MONEY,
	TOTPAGFAC MONEY,
    CONSTRAINT FACTURA_pk PRIMARY KEY  (CODFAC)
);
-- Table: DETALLE_FACTURA
CREATE TABLE DETALLE_FACTURA (
    CODFAC int ,
    IDPROD int ,
    CANTDET int  ,
    SUBTOTDET MONEY  ,
    CONSTRAINT DETALLE_pk PRIMARY KEY  (IDDET)
);


-- Table: PRODUCTO
CREATE TABLE PRODUCTO (
    IDPROD int IDENTITY(1,1) ,
    NOMPROD varchar(50)  ,
	DESCPPROD varchar(50)  ,
    PRECPROD money ,
    STOCK int  ,
    CONSTRAINT PRODUCTO_pk PRIMARY KEY  (IDPROD)
);

-- Reference: FACTURA (table:FACTURA)
ALTER TABLE FACTURA ADD CONSTRAINT FACTURA_DETALLE_FACTURA
    FOREIGN KEY (IDDET)
    REFERENCES FACTURA_DETALLE (IDDET);

-- Reference: DETALLE_FACTURA_PRODUCTO (table: DETALLE_FACTURA)
ALTER TABLE DETALLE_FACTURA ADD CONSTRAINT DETALLE_FACTURA_PRODUCTO
    FOREIGN KEY (IDPROD)
    REFERENCES PRODUCTO (IDPROD);

-- Reference: FACTURA_CLIENTE (table: FACTURA)
ALTER TABLE FACTURA ADD CONSTRAINT FACTURA_CLIENTE
    FOREIGN KEY (IDCLI)
    REFERENCES CLIENTE (IDCLI);