DROP DATABASE PUNTOVENTA;
CREATE DATABASE PUNTOVENTA;
USE PUNTOVENTA;
-- tables
-- Table: CATEGORIA
CREATE TABLE CATEGORIA (
    IDCAT int  IDENTITY(1,1) ,
    NOMCAT varchar(50)  ,
    DESCAT varchar(100)  ,
    CONSTRAINT CATEGORIA_pk PRIMARY KEY  (IDCAT)
);

-- Table: CLIENTE
CREATE TABLE CLIENTE (
    IDCLI int IDENTITY(1,1),
    NOMCLI varchar(50),
    APEPATCLI varchar(50),
    APEMATCLI varchar(50) ,
    FECNACCLI date ,
    DIRCLI varchar(50),
    TELFCLI CHAR(9),
    EMAILCLI varchar(50) ,
    CONSTRAINT CLIENTE_pk PRIMARY KEY  (IDCLI)
);

-- Table: DETALLE
CREATE TABLE DETALLE (
    IDDET int IDENTITY(1,1) ,
    CODFAC int ,
    IDPROD int ,
    CANTDET int  ,
    PRICTOTDET money  ,
    CONSTRAINT DETALLE_pk PRIMARY KEY  (IDDET)
);

-- Table: FACTURA
CREATE TABLE FACTURA (
    CODFAC int  NOT NULL,
    IDCLI int  ,
    FECHFAC date  ,
    IDPAG int  ,
    CONSTRAINT FACTURA_pk PRIMARY KEY  (CODFAC)
);

-- Table: MODO_PAGO
CREATE TABLE MODO_PAGO (
    IDPAG int IDENTITY(1,1) ,
    NOMPAG varchar(50)  ,
    DETALPAG varchar(50) ,
    CONSTRAINT MODO_PAGO_pk PRIMARY KEY  (IDPAG)
);

-- Table: PRODUCTO
CREATE TABLE PRODUCTO (
    IDPROD int ,
    NOMPROD varchar(50)  ,
    PRICPROD money ,
    STOCK int  ,
    IDCAT int  ,
    CONSTRAINT PRODUCTO_pk PRIMARY KEY  (IDPROD)
);

-- Reference: DETALLE_FACTURA (table: DETALLE)
ALTER TABLE DETALLE ADD CONSTRAINT DETALLE_FACTURA
    FOREIGN KEY (CODFAC)
    REFERENCES FACTURA (CODFAC);

-- Reference: DETALLE_PRODUCTO (table: DETALLE)
ALTER TABLE DETALLE ADD CONSTRAINT DETALLE_PRODUCTO
    FOREIGN KEY (IDPROD)
    REFERENCES PRODUCTO (IDPROD);

-- Reference: FACTURA_CLIENTE (table: FACTURA)
ALTER TABLE FACTURA ADD CONSTRAINT FACTURA_CLIENTE
    FOREIGN KEY (IDCLI)
    REFERENCES CLIENTE (IDCLI);

-- Reference: FACTURA_MODO_PAGO (table: FACTURA)
ALTER TABLE FACTURA ADD CONSTRAINT FACTURA_MODO_PAGO
    FOREIGN KEY (IDPAG)
    REFERENCES MODO_PAGO (IDPAG);

-- Reference: PRODUCTO_CATEGORIA (table: PRODUCTO)
ALTER TABLE PRODUCTO ADD CONSTRAINT PRODUCTO_CATEGORIA
    FOREIGN KEY (IDCAT)
    REFERENCES CATEGORIA (IDCAT);

